
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * add_venue.java
 *
 * Created on 6 Apr, 2019, 10:57:59 AM
 */
/**
 *
 * @author Sarthak
 */
public class add_venue extends javax.swing.JFrame {

    /** Creates new form add_venue */
    public static admin_portal lpg;
    public add_venue(admin_portal lpg) {
        this.lpg=lpg;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        cap = new javax.swing.JTextField();
        vclass = new javax.swing.JCheckBox();
        audi = new javax.swing.JCheckBox();
        lab = new javax.swing.JCheckBox();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pro = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-12783376,true));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(-12128016,true));
        jLabel1.setFont(new java.awt.Font("Serif", 0, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD NEW VENUE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 30, 290, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 130, 110, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel3.setText("Capacity:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 200, 90, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel4.setText("Venue type:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 260, 80, 40);
        jPanel1.add(name_field);
        name_field.setBounds(390, 130, 170, 30);
        jPanel1.add(cap);
        cap.setBounds(390, 200, 170, 30);

        vclass.setBackground(new java.awt.Color(-12783376,true));
        vclass.setText("Class");
        vclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vclassActionPerformed(evt);
            }
        });
        jPanel1.add(vclass);
        vclass.setBounds(390, 270, 110, 23);

        audi.setBackground(new java.awt.Color(-12783376,true));
        audi.setText("Audotorium");
        audi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiActionPerformed(evt);
            }
        });
        jPanel1.add(audi);
        audi.setBounds(390, 310, 130, 23);

        lab.setBackground(new java.awt.Color(-12783376,true));
        lab.setText("Lab");
        lab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labActionPerformed(evt);
            }
        });
        jPanel1.add(lab);
        lab.setBounds(390, 350, 100, 23);

        back.setBackground(new java.awt.Color(-1,true));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(650, 40, 90, 30);

        submit.setBackground(new java.awt.Color(-1,true));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(350, 460, 120, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel5.setText("Hardwares:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 390, 80, 40);

        pro.setBackground(new java.awt.Color(-12783376,true));
        pro.setText("Projector");
        jPanel1.add(pro);
        pro.setBounds(390, 400, 120, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String s=name_field.getText(),cp=cap.getText();
        if(s.isEmpty() || cp.isEmpty() || (!(vclass.isSelected() || audi.isSelected() || lab.isSelected())))
        JOptionPane.showMessageDialog(this,"Please enter values for all fields.");

    else
    {
        int c=Integer.parseInt(cp);
        String r="",pr="",cl="",au="",l="";
        long mills=System.currentTimeMillis();
        java.sql.Date t=new java.sql.Date(mills);                   
        if(pro.isSelected())pr="Projector";
        if(vclass.isSelected())cl="Class";
        if(audi.isSelected())au="Audotorium";
        if(lab.isSelected())l="Lab";
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagement","root","");
            Statement st = (Statement) con.createStatement();
            String query="INSERT INTO venues VALUES ('"+s+"','"+c+"','"+r+"','"+t+"','"+pr+"','"+cl+"','"+au+"','"+l+"');";
            st.executeUpdate(query);      
            JOptionPane.showMessageDialog(this,"Successfully added venue.");
            lpg.setVisible(true);
            this.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"There was an error connecting to database.");
        }
    }
}//GEN-LAST:event_submitActionPerformed

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

    lpg.setVisible(true);
    this.dispose();
    
}//GEN-LAST:event_backActionPerformed

private void labActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labActionPerformed

    if(lab.isSelected()){audi.setSelected(false); vclass.setSelected(false);}
    
}//GEN-LAST:event_labActionPerformed

private void audiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiActionPerformed

    if(audi.isSelected()){vclass.setSelected(false); lab.setSelected(false);}
    
}//GEN-LAST:event_audiActionPerformed

private void vclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vclassActionPerformed

    if(vclass.isSelected()){audi.setSelected(false); lab.setSelected(false);}
    
}//GEN-LAST:event_vclassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new add_venue(lpg).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox audi;
    private javax.swing.JButton back;
    private javax.swing.JTextField cap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox lab;
    private javax.swing.JTextField name_field;
    private javax.swing.JCheckBox pro;
    private javax.swing.JButton submit;
    private javax.swing.JCheckBox vclass;
    // End of variables declaration//GEN-END:variables
}
