
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import com . mysql. jdbc . Connection;
import com.mysql.jdbc.Statement;
import java.sql.Date;
import java.sql.ResultSet;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cancel_event.java
 *
 * Created on 2 Apr, 2019, 9:53:24 AM
 */
/**
 *
 * @author Sarthak
 */
public class cancel_event extends javax.swing.JFrame {

    /** Creates new form cancel_event */
    public static stu_fac_login lpg;
    public static String who,what;
    public ResultSet rs;
    public Connection con=null;
    public Statement st;
    public cancel_event(stu_fac_login lpg,String who,String what) {
        this.lpg=lpg;
        this.who=who;
        this.what=what;
        initComponents();
        start();
    }
    private void start()
    {
        try 
        {
            Class.forName("java.sql.DriverManager");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagement","root", "");
            st = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            Date date=new Date(System.currentTimeMillis());
            String ct=date.toString();
            String srt="SELECT * FROM `events` where creator = '"+who+"' and date >= '"+ct+"'  order by date";
            rs=st.executeQuery(srt);
            if(rs.next())
            {
                op.setVisible(false);
                String ena=rs.getString("event"),edes=rs.getString("desc"),edat=rs.getDate("date").toString(),etim=rs.getString("time"),even=rs.getString("evenue");
                ename.setText(ena);
                edesc.setText(edes);
                edate.setText(edat);
                etime.setText(etim);
                evenue.setText(even);      
            }   
            else
            {
                lp.setVisible(false);
                op.setVisible(true);
                next.setVisible(false);
                prev.setVisible(false);
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        lp = new javax.swing.JLayeredPane();
        confirm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        edesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        etime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        evenue = new javax.swing.JTextField();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        op = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-12128016,true));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CANCEL EVENTS");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarthak\\Desktop\\mp\\event.jpg")); // NOI18N

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        lp.setBackground(new java.awt.Color(-1,true));
        lp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-14336,true), 5));

        confirm.setText("Cancel");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        confirm.setBounds(270, 243, 90, 30);
        lp.add(confirm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Name:");
        jLabel3.setBounds(24, 50, 50, 14);
        lp.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Description:");
        jLabel5.setBounds(20, 120, 70, 20);
        lp.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ename.setBounds(110, 40, 170, 30);
        lp.add(ename, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edesc.setBounds(110, 110, 170, 80);
        lp.add(edesc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Date:");
        jLabel4.setBounds(370, 40, 60, 30);
        lp.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edateActionPerformed(evt);
            }
        });
        edate.setBounds(450, 40, 120, 30);
        lp.add(edate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Time:");
        jLabel6.setBounds(370, 100, 60, 30);
        lp.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        etime.setBounds(450, 100, 120, 30);
        lp.add(etime, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Venue:");
        jLabel7.setBounds(370, 160, 50, 30);
        lp.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        evenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evenueActionPerformed(evt);
            }
        });
        evenue.setBounds(450, 160, 120, 30);
        lp.add(evenue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prev.setBackground(new java.awt.Color(-1,true));
        prev.setText("prev");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        next.setBackground(new java.awt.Color(-1,true));
        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        op.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        op.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op.setText("YOU HAVE  NO EVENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lp, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lp, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

    lpg.setVisible(true);
    this.dispose();
}//GEN-LAST:event_backActionPerformed

private void edateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edateActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_edateActionPerformed

private void evenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evenueActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_evenueActionPerformed

private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        try 
        {
            if(!rs.previous())rs.last();
            String ena=rs.getString("event"),edes=rs.getString("desc"),edat=rs.getDate("date").toString(),etim=rs.getString("time"),even=rs.getString("evenue");
                ename.setText(ena);
                edesc.setText(edes);
                edate.setText(edat);
                etime.setText(etim);
                evenue.setText(even);
            
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this,"Unexpected error occured.");
        }
    
}//GEN-LAST:event_prevActionPerformed

private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

    try 
        {
            if(!rs.next())rs.first();
            String ena=rs.getString("event"),edes=rs.getString("desc"),edat=rs.getDate("date").toString(),etim=rs.getString("time"),even=rs.getString("evenue");
                ename.setText(ena);
                edesc.setText(edes);
                edate.setText(edat);
                etime.setText(etim);
                evenue.setText(even);
            
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this,"Unexpected error occured.");
        }
    
}//GEN-LAST:event_nextActionPerformed

private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed

        try 
        {
            String edat=rs.getDate("date").toString(),etim=rs.getString("time"),even=rs.getString("evenue"),quer;
            quer="DELETE FROM `events` WHERE date = '"+edat+"' and time = '"+etim+"' and evenue = '"+even+"'  ;";
            st.executeUpdate(quer);
            start();
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, "Could not update.");
        }
    
}//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancel_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancel_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancel_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancel_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new cancel_event(lpg,who,what).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField edate;
    private javax.swing.JTextField edesc;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField etime;
    private javax.swing.JTextField evenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane lp;
    private javax.swing.JButton next;
    private javax.swing.JLabel op;
    private javax.swing.JButton prev;
    // End of variables declaration//GEN-END:variables
}
