/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 3 Apr, 2019, 6:08:17 PM
 */
/**
 *
 * @author Sarthak
 */
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import com . mysql. jdbc . Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        teacherbotton = new javax.swing.JButton();
        adminbutton = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        passfield = new javax.swing.JPasswordField();
        cover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 120, 70, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 180, 70, 30);
        jPanel1.add(loginfield);
        loginfield.setBounds(330, 120, 150, 30);

        jButton1.setText("Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 430, 110, 23);

        teacherbotton.setText("Teacher");
        teacherbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherbottonActionPerformed(evt);
            }
        });
        jPanel1.add(teacherbotton);
        teacherbotton.setBounds(300, 430, 110, 23);

        adminbutton.setText("Administrator");
        adminbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(adminbutton);
        adminbutton.setBounds(480, 430, 110, 23);

        jTextField3.setBackground(new java.awt.Color(-4259841,true));
        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Dialog", 0, 24));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("EVENT MANAGEMENT SYSTEM");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(0, 20, 720, 60);

        jTextField4.setBackground(new java.awt.Color(-4259841,true));
        jTextField4.setFont(new java.awt.Font("Dialog", 0, 14));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Login As:");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(0, 240, 110, 40);
        jPanel1.add(passfield);
        passfield.setBounds(330, 180, 150, 30);

        cover.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarthak\\Desktop\\mp\\back.jpg")); // NOI18N
        jPanel1.add(cover);
        cover.setBounds(0, 0, 720, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    String id=loginfield.getText(),pass=new String(passfield.getPassword());
    if(id.isEmpty() || pass.isEmpty())
        JOptionPane.showMessageDialog(this,"Please enter username and password.");
    
    else
    {
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagement","root", "");
            Statement st = (Statement) con.createStatement();
            String query="SELECT * FROM users WHERE loginid='"+id+"' and password='"+pass+"'and usert='Student';";
            ResultSet rs=st.executeQuery(query);
            if(rs.next())
            {
                loginfield.setText("");
                passfield.setText("");
                stu_fac_login pg=new stu_fac_login(this,id,"Student");
                pg.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Sorry!! No such account found.");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"There was an error connecting to database.");
        }
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void adminbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbuttonActionPerformed

    String id=loginfield.getText(),pass=new String(passfield.getPassword());
    if(id.isEmpty() || pass.isEmpty())
        JOptionPane.showMessageDialog(this,"Please enter username and password.");
    
    else
    {
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagement","root", "");
            Statement st = (Statement) con.createStatement();
            String query="SELECT * FROM users WHERE loginid='"+id+"' and password='"+pass+"'and usert='admin';";
            ResultSet rs=st.executeQuery(query);
            if(rs.next())
            {
                loginfield.setText("");
                passfield.setText("");
                admin_portal pg=new admin_portal(this,id,"Admin");
                pg.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Sorry!! No such account found.");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"There was an error connecting to database.");
        }
    }
    
    
}//GEN-LAST:event_adminbuttonActionPerformed

private void teacherbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherbottonActionPerformed

    
    String id=loginfield.getText(),pass=new String(passfield.getPassword());
    if(id.isEmpty() || pass.isEmpty())
        JOptionPane.showMessageDialog(this,"Please enter username and password.");
    
    else
    {
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagement","root", "");
            Statement st = (Statement) con.createStatement();
            String query="SELECT * FROM users WHERE loginid='"+id+"' and password='"+pass+"'and usert='Teacher';";
            ResultSet rs=st.executeQuery(query);
            if(rs.next())
            {
                loginfield.setText("");
                passfield.setText("");
                stu_fac_login pg=new stu_fac_login(this,id,"Teacher");
                pg.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Sorry!! No such account found.");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"There was an error connecting to database.");
        }
    }
    
}//GEN-LAST:event_teacherbottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbutton;
    private javax.swing.JLabel cover;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField loginfield;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JButton teacherbotton;
    // End of variables declaration//GEN-END:variables
}
