
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * stu_viewevents.java
 *
 * Created on 14 Apr, 2019, 11:52:52 PM
 */
/**
 *
 * @author Sarthak
 */
public class stu_viewevents extends javax.swing.JFrame {

    /** Creates new form stu_viewevents */
    public static stu_fac_login lpg;
    public static int f;
    public ResultSet rs;
    public Connection con=null;
    public Statement st;
    public stu_viewevents(stu_fac_login lpg,int f) {
        initComponents();
        this.lpg=lpg;
        this.f=f;
        start();
    }
    private void start()
    {
        try 
        {
            if(f==1)head.setText("UPCOMING EVENTS"); else head.setText("PAST EVENTS");
            Class.forName("java.sql.DriverManager");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/eventmanagement","root", "");
            st = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            Date date=new Date(System.currentTimeMillis());
            String ct=date.toString(),srt;
            if(f==2)
            srt="SELECT * FROM `events` where date < '"+ct+"' and fix='Yes' order by date DESC ;";
            else srt="SELECT * FROM `events` where date >= '"+ct+"' and fix='Yes' order by date ;";
            rs=st.executeQuery(srt);
            if(rs.next())
            {
                op.setVisible(false);
                String ena=rs.getString("event"),edes=rs.getString("desc"),edat=rs.getDate("date").toString(),etim=rs.getString("time"),even=rs.getString("evenue");
                ename.setText(ena);
                edesc.setText(edes);
                edate.setText(edat);
                etime.setText(etim);
                evenue.setText(even);      
            }   
            else
            {
                lp.setVisible(false);
                op.setVisible(true);
                next.setVisible(false);
                prev.setVisible(false);
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lp = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        edesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        etime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        evenue = new javax.swing.JTextField();
        head = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        op = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-14094096,true));

        lp.setBackground(new java.awt.Color(-1,true));
        lp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-14336,true), 5));

        jLabel3.setText("Name:");
        jLabel3.setBounds(24, 50, 50, 14);
        lp.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Description:");
        jLabel5.setBounds(20, 160, 70, 20);
        lp.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ename.setBounds(110, 40, 170, 30);
        lp.add(ename, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edesc.setBounds(110, 160, 170, 80);
        lp.add(edesc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Date:");
        jLabel4.setBounds(370, 40, 60, 30);
        lp.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edateActionPerformed(evt);
            }
        });
        edate.setBounds(450, 40, 120, 30);
        lp.add(edate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Time:");
        jLabel6.setBounds(370, 120, 60, 30);
        lp.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        etime.setBounds(450, 120, 120, 30);
        lp.add(etime, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Venue:");
        jLabel7.setBounds(370, 200, 50, 30);
        lp.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        evenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evenueActionPerformed(evt);
            }
        });
        evenue.setBounds(450, 200, 120, 30);
        lp.add(evenue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        head.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sarthak\\Desktop\\mp\\event.jpg")); // NOI18N

        back.setBackground(new java.awt.Color(-1,true));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        prev.setText("Prev");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        op.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        op.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op.setText("NO EVENTS TO DISPLAY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lp, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addComponent(lp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void edateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edateActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_edateActionPerformed

private void evenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evenueActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_evenueActionPerformed

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

    lpg.setVisible(true);
    this.dispose();
    
}//GEN-LAST:event_backActionPerformed

private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

    try 
        {
            if(!rs.next())rs.first();
            String ena=rs.getString("event"),edes=rs.getString("desc"),edat=rs.getDate("date").toString(),etim=rs.getString("time"),even=rs.getString("evenue");
                ename.setText(ena);
                edesc.setText(edes);
                edate.setText(edat);
                etime.setText(etim);
                evenue.setText(even);
            
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this,"Unexpected error occured.");
        }
    
}//GEN-LAST:event_nextActionPerformed

private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed

    try 
        {
            if(!rs.previous())rs.last();
            String ena=rs.getString("event"),edes=rs.getString("desc"),edat=rs.getDate("date").toString(),etim=rs.getString("time"),even=rs.getString("evenue");
                ename.setText(ena);
                edesc.setText(edes);
                edate.setText(edat);
                etime.setText(etim);
                evenue.setText(even);
            
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this,"Unexpected error occured.");
        }
    
}//GEN-LAST:event_prevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stu_viewevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stu_viewevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stu_viewevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stu_viewevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new stu_viewevents(lpg,f).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField edate;
    private javax.swing.JTextField edesc;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField etime;
    private javax.swing.JTextField evenue;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane lp;
    private javax.swing.JButton next;
    private javax.swing.JLabel op;
    private javax.swing.JButton prev;
    // End of variables declaration//GEN-END:variables
}
